### ISSUE TITLE
error make

### ISSUE THREAD

**Issue by modInfo** [adtac/fssb#2]
root@aksus:~/fssb# make
cc    -c -o fssb.o fssb.c
fssb.c: In function ‘handle_syscalls’:
fssb.c:73:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
         for(int i = 0; i < 6; i++)
         ^
fssb.c:73:9: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code

yes, openssl is istalled, debian 8

**Comment by adtac** [comment]
Hi, thanks for filing this issue.

The issue seems to be with declaring the index variable inside the loop. [I have added a patch](https://github.com/adtac/fssb/commit/7949c6c9a500a715f08eddccbe5f0d183485a5c4) that should fix this (this was happening at 3 different places - fixed them all). Can you pull the latest from master and try compiling again?

**Comment by modInfo** [comment]
Now works! Thanks for great project!
